(5-3)上級 パスワード暗号化orハッシュ化
terassy-organization/ex-emp-management-bugfix pull request #14
Opened 2024-06-10 06:41 UTC by yusaku-terashima

登録されるパスワードをハッシュ化し、それを用いてログインするようにしました。確認お願いします。

2024-06-10 08:53 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-10 08:53 UTC, igamasayuki commented on src/main/resources/Pom.xml
> +</dependency>
pom.xmlはmavenというビルドツールの設定ファイルです。

今回はGradleを使っているのでbuild.gradleにこのライブラリを追加する記述を１行書いてください。

2024-06-10 08:57 UTC, yusaku-terashima commented
pom.xmlを削除したので確認お願いします。

2024-06-11 01:35 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-11 01:35 UTC, merged